### Schema

CREATE TABLE USERS
(
	USER_ID INT NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(30) NOT NULL,
	PRIMARY KEY (USER_ID)
);

CREATE TABLE ATTR
(
	ATTR_ID INT NOT NULL AUTO_INCREMENT,
	USER_ID INT NOT NULL,
	ATTR_NAME VARCHAR(30)NOT NULL,
    CITY VARCHAR(30)NOT NULL,
	COUNTRY VARCHAR(30)NOT NULL,
	PRIMARY KEY (ATTR_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);