CREATE TABLE USERS
(
ID INT NOT NULL AUTO_INCREMENT,
	USER_EMAIL VARCHAR(30) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ATTR
(
	ATTR_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(30),
	ATTR_NAME VARCHAR(30)NOT NULL,
    CITY VARCHAR(30)NOT NULL,
    STATE VARCHAR(30),
	COUNTRY VARCHAR(30)NOT NULL,
	PRIMARY KEY (ATTR_ID)
);