CREATE TABLE USERATTR
(
ID INT NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(30) NOT NULL,
ATTR_NAME VARCHAR(30)NOT NULL,
CITY VARCHAR(30)NOT NULL,
STATE VARCHAR(30) NULL,
COUNTRY VARCHAR(30) NOT NULL,
PRIMARY KEY (ID)
);