	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, COUNTRY)
	VALUES ("trip_person","LITTLE VENICE", "LONDON", "UK");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, COUNTRY)
	VALUES ("trip_person","PIE AND MASH SHOPS", "LONDON", "UK");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, COUNTRY)
	VALUES ("vacaygirl","ELS ENCANTS FLEA MARKET", "BARCELONA", "SPAIN");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, COUNTRY)
	VALUES ("vacaygirl","BUNKERS DEL CARMEL", "BARCELONA", "SPAIN");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, COUNTRY)
	VALUES ("vacaygirl","BARCELONA ICE BAR", "BARCELONA", "SPAIN");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, STATE, COUNTRY)
	VALUES ("KIB48885","THE WHISPERING GALLERYT", "NEW YORK CITY", "NY", "USA");
	INSERT INTO USERATTR (USERNAME, ATTR_NAME, CITY, STATE, COUNTRY)
	VALUES ("KIB48885","WATER STREET ROOFTOP",  "NEW YORK CITY", "NY", "USA");
