INSERT INTO USERS (user_email, USERNAME)
VALUES ("trip_personUSER_EMAILa@GMAIL.COM","Kevin Ferguson");
select * from USERS;

INSERT INTO USERS (user_email, USERNAME)
VALUES ("vacaygirl@GMAIL.COM", "vacaygirl" );

INSERT INTO USERS (user_email, username)
VALUES ("KIB48885@GMAIL.COM", "kib48885" );

INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, COUNTRY)
VALUES (1,"LITTLE VENICE", "LONDON", "UK");

INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, COUNTRY)
VALUES (1,"PIE AND MASH SHOPS", "LONDON", "UK");


INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, COUNTRY)
VALUES (2, "ELS ENCANTS FLEA MARKET", "BARCELONA", "SPAIN");

INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, COUNTRY)
VALUES (2,"BUNKERS DEL CARMEL", "BARCELONA", "SPAIN");

INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, COUNTRY)
VALUES (2,"BARCELONA ICE BAR", "BARCELONA", "SPAIN");



INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, STATE, COUNTRY)
VALUES (3,"THE WHISPERING GALLERYT", "NEW YORK CITY", "NY", "USA");

INSERT INTO ATTR (USER_ID, ATTR_NAME, CITY, STATE, COUNTRY)
VALUES (3,"WATER STREET ROOFTOP",  "NEW YORK CITY", "NY", "USA");


select * from ATTR
